language: node_js
node_js:
- lts/*
script:
- npm run build
notifications:
  email: false
deploy:
  - provider: pages
    local_dir: docs
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    keep-history: true
    verbose: true
    on:
      branch: master
  - provider: npm
    email: sziklaszlo@gmail.com
    api_key:
      secure: TBD
    on:
      branch: master
      tags: true